### PR TITLE
Pokemon Search App

### PR DESCRIPTION
**Pull request by zainabbehzad**
Pokemon Search App:
* First of all I created the repo according the project requirements.
* Followed the Gitflow.
* Setup the Linters configuration for my project.
* Created HTML, CSS, and JavaScript files to create structure of my project by HTML codes, added design to my project by CSS codes, and added functionality to my project by JavaScript codes.
* Made responsive my project.
* Added README.md file to my project.
* When I finished my project test the codes in FreeCodeCamp and passes all it's requirements.

Screenshot (57)

### CODE REVIEW

**Comment by zainabbehzad** [comment]
@Marwa-Sadat
Hi Marwa jan please review my project.

**Comment by zainabbehzad** [comment]
@ahzamir
Hello Dear Sir!
Please review my project.
Sir as my partner is not home and for now she can not review my project, in this case I mentioned you to review my project as the deadline of project is tonight.

**Review by ahzamir — CHANGES_REQUESTED** [review]
@zainabbehzad 

- Well done you have implemented lots of requirements but still your project responsiveness has some issues please solve them and mention me again here in your pull-request for a re-review:

image

**Review by ahzamir — APPROVED** [review]
### Hi @zainabbehzad 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by zainabbehzad** [comment]
@ahzamir 
Thanks sir!

**Pull request merged**
